// Quotes shown while a board is loading — sourced from Ben's curated
// Quotes_Work_Lean_People spreadsheet (work, lean, people themes).

export interface Quote {
  q: string;
  by: string;
}

export const QUOTES: Quote[] = [
  { q: "Choose a job you love, and you will never have to work a day in your life.", by: "Confucius" },
  { q: "The only way to do great work is to love what you do.", by: "Steve Jobs" },
  { q: "Work is love made visible.", by: "Kahlil Gibran" },
  { q: "Far and away the best prize that life offers is the chance to work hard at work worth doing.", by: "Theodore Roosevelt" },
  { q: "Pleasure in the job puts perfection in the work.", by: "Aristotle" },
  { q: "Without labour nothing prospers.", by: "Sophocles" },
  { q: "The reward of a thing well done is having done it.", by: "Ralph Waldo Emerson" },
  { q: "Nothing will work unless you do.", by: "Maya Angelou" },
  { q: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", by: "Thomas Edison" },
  { q: "Genius is one percent inspiration and ninety-nine percent perspiration.", by: "Thomas Edison" },
  { q: "The future depends on what you do today.", by: "Mahatma Gandhi" },
  { q: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", by: "Will Durant, on Aristotle" },
  { q: "Amateurs sit and wait for inspiration; the rest of us just get up and go to work.", by: "Stephen King" },
  { q: "The only place success comes before work is in the dictionary.", by: "Vince Lombardi" },
  { q: "Hard work beats talent when talent doesn't work hard.", by: "Tim Notke" },
  { q: "Do what you can, with what you have, where you are.", by: "Theodore Roosevelt" },
  { q: "Whatever your hand finds to do, do it with all your might.", by: "Solomon" },
  { q: "Well done is better than well said.", by: "Benjamin Franklin" },
  { q: "By failing to prepare, you are preparing to fail.", by: "Benjamin Franklin" },
  { q: "Success is the sum of small efforts repeated day in and day out.", by: "Robert Collier" },
  { q: "The secret of getting ahead is getting started.", by: "Mark Twain" },
  { q: "Action is the foundational key to all success.", by: "Pablo Picasso" },
  { q: "It always seems impossible until it's done.", by: "Nelson Mandela" },
  { q: "Start where you are. Use what you have. Do what you can.", by: "Arthur Ashe" },
  { q: "Perseverance is not a long race; it is many short races one after another.", by: "Walter Elliot" },
  { q: "Discipline is the bridge between goals and accomplishment.", by: "Jim Rohn" },
  { q: "You don't have to be great to start, but you have to start to be great.", by: "Zig Ziglar" },
  { q: "There are no shortcuts to any place worth going.", by: "Beverly Sills" },
  { q: "Do the hard jobs first. The easy jobs will take care of themselves.", by: "Dale Carnegie" },
  { q: "Concentrate all your thoughts upon the work at hand.", by: "Alexander Graham Bell" },
  { q: "A dream doesn't become reality through magic; it takes sweat, determination, and hard work.", by: "Colin Powell" },
  { q: "I'm a great believer in luck, and the harder I work the more I have of it.", by: "Thomas Jefferson" },
  { q: "Nothing worth having comes except as a result of hard work.", by: "Booker T. Washington" },
  { q: "Dripping water hollows out stone, not through force but through persistence.", by: "Ovid" },
  { q: "The most dangerous kind of waste is the waste we do not recognise.", by: "Shigeo Shingo" },
  { q: "Where there is no standard, there can be no kaizen.", by: "Taiichi Ohno" },
  { q: "Improvement usually means doing something we have never done before.", by: "Shigeo Shingo" },
  { q: "Costs do not exist to be calculated. Costs exist to be reduced.", by: "Taiichi Ohno" },
  { q: "Having no problems is the biggest problem of all.", by: "Taiichi Ohno" },
  { q: "Progress cannot be generated when we are satisfied with existing situations.", by: "Taiichi Ohno" },
  { q: "It is not enough to do your best; you must know what to do, and then do your best.", by: "W. Edwards Deming" },
  { q: "A bad system will beat a good person every time.", by: "W. Edwards Deming" },
  { q: "Without data, you're just another person with an opinion.", by: "W. Edwards Deming" },
  { q: "If you can't describe what you're doing as a process, you don't know what you're doing.", by: "W. Edwards Deming" },
  { q: "It is not necessary to change. Survival is not mandatory.", by: "W. Edwards Deming" },
  { q: "Cease dependence on inspection to achieve quality.", by: "W. Edwards Deming" },
  { q: "Quality is not an act, it is a habit.", by: "Aristotle" },
  { q: "Quality means doing it right when no one is looking.", by: "Henry Ford" },
  { q: "Nothing is particularly hard if you divide it into small jobs.", by: "Henry Ford" },
  { q: "Time waste differs from material waste in that there can be no salvage.", by: "Henry Ford" },
  { q: "If you always do what you've always done, you'll always get what you've always got.", by: "Henry Ford" },
  { q: "Whether you think you can or think you can't, you're right.", by: "Henry Ford" },
  { q: "There is nothing so useless as doing efficiently that which should not be done at all.", by: "Peter Drucker" },
  { q: "Efficiency is doing things right; effectiveness is doing the right things.", by: "Peter Drucker" },
  { q: "What gets measured gets managed.", by: "Peter Drucker" },
  { q: "The best way to predict the future is to create it.", by: "Peter Drucker" },
  { q: "Culture eats strategy for breakfast.", by: "Peter Drucker" },
  { q: "Perfection is not attainable, but if we chase perfection we can catch excellence.", by: "Vince Lombardi" },
  { q: "Continuous improvement is better than delayed perfection.", by: "Mark Twain" },
  { q: "Simplicity is the ultimate sophistication.", by: "Leonardo da Vinci" },
  { q: "Everything should be made as simple as possible, but not simpler.", by: "Albert Einstein" },
  { q: "A goal without a plan is just a wish.", by: "Antoine de Saint-Exupery" },
  { q: "Vision without action is a daydream; action without vision is a nightmare.", by: "Japanese proverb" },
  { q: "Fall seven times, stand up eight.", by: "Japanese proverb" },
  { q: "The goal of lean is to eliminate waste, not people.", by: "Lean maxim" },
  { q: "Measure twice, cut once.", by: "Carpenter's proverb" },
  { q: "Slow is smooth, and smooth is fast.", by: "Operational proverb" },
  { q: "No act of kindness, no matter how small, is ever wasted.", by: "Aesop" },
  { q: "Be kind, for everyone you meet is fighting a hard battle.", by: "Ian Maclaren" },
  { q: "People will forget what you said and did, but never how you made them feel.", by: "Maya Angelou" },
  { q: "The best way to find yourself is to lose yourself in the service of others.", by: "Mahatma Gandhi" },
  { q: "We rise by lifting others.", by: "Robert Ingersoll" },
  { q: "Kindness is a language the deaf can hear and the blind can see.", by: "Mark Twain" },
  { q: "Treat people as if they were what they ought to be, and you help them become it.", by: "Johann Wolfgang von Goethe" },
  { q: "Do unto others as you would have them do unto you.", by: "Jesus of Nazareth" },
  { q: "Alone we can do so little; together we can do so much.", by: "Helen Keller" },
  { q: "Talent wins games, but teamwork and intelligence win championships.", by: "Michael Jordan" },
  { q: "If you want to go fast, go alone. If you want to go far, go together.", by: "African proverb" },
  { q: "None of us is as smart as all of us.", by: "Ken Blanchard" },
  { q: "The strength of the team is each member; the strength of each member is the team.", by: "Phil Jackson" },
  { q: "Respect for ourselves guides our morals; respect for others guides our manners.", by: "Laurence Sterne" },
  { q: "Try to be a rainbow in someone's cloud.", by: "Maya Angelou" },
  { q: "Leadership is not about being in charge. It is about taking care of those in your charge.", by: "Simon Sinek" },
  { q: "A leader is one who knows the way, goes the way, and shows the way.", by: "John C. Maxwell" },
  { q: "Take care of your employees and they'll take care of your clients.", by: "Richard Branson" },
  { q: "Individually we are one drop. Together we are an ocean.", by: "Ryunosuke Satoro" },
  { q: "Kind words can be short and easy to speak, but their echoes are truly endless.", by: "Mother Teresa" },
  { q: "We make a living by what we get, but we make a life by what we give.", by: "Winston Churchill" },
  { q: "Carry each other's burdens.", by: "Paul of Tarsus" },
  { q: "A candle loses nothing by lighting another candle.", by: "James Keller" },
  { q: "Wherever there is a human being, there is an opportunity for kindness.", by: "Seneca" },
  { q: "How wonderful that nobody need wait a single moment before starting to improve the world.", by: "Anne Frank" },
  { q: "Never look down on anybody unless you're helping them up.", by: "Jesse Jackson" },
  { q: "You can judge a person's character by how they treat those who can do nothing for them.", by: "Malcolm Forbes" },
  { q: "In the end, we will remember not the words of our enemies, but the silence of our friends.", by: "Martin Luther King Jr." },
  { q: "The measure of a man is what he does with power.", by: "Plato" },
  { q: "A person who feels appreciated will always do more than expected.", by: "Workplace maxim" },
  { q: "Coming together is a beginning, keeping together is progress, working together is success.", by: "Edward Everett Hale" },
  { q: "Everyone you meet knows something you don't.", by: "Bill Nye" },
  { q: "Encourage one another and build each other up.", by: "Paul of Tarsus" },
  { q: "By perseverance the snail reached the ark.", by: "Charles Spurgeon" },
  { q: "The first service one owes to others in a community consists of listening to them.", by: "Dietrich Bonhoeffer" },
];
